Repository kubernetes-csi/external-snapshot-metadata, pull requests merged in 2024-12, with the labels that each got.

#81 add support for custom SA namespace in snap meta lister tool
  examples/snapshot-metadata-lister/main.go
  pkg/iterator/common_test.go
  pkg/iterator/iter.go
  pkg/iterator/iter_test.go
Labels: kind/bug, release-note-none, size/L, approved, lgtm, needs-ok-to-test, cncf-cla: yes

#84 Add tls secrets and CR for e2e test setup
  deploy/example/csi-driver/testdata/certs/ca-cert.pem
  deploy/example/csi-driver/testdata/certs/server-cert.pem
  deploy/example/csi-driver/testdata/certs/server-key.pem
  deploy/example/csi-driver/testdata/csi-snapshot-metadata-service.yaml
  deploy/example/csi-driver/testdata/csi-snapshot-metadata-tls-secret.yaml
  deploy/example/csi-driver/testdata/snapshotmetadataservice.yaml
Labels: release-note-none, size/L, approved, lgtm, cncf-cla: yes

#83 Sync Release tools repo subtree
  release-tools/build.make
  release-tools/prow.sh
  release-tools/pull-test.sh
Labels: release-note-none, ok-to-test, kind/failing-test, size/M, approved, lgtm, cncf-cla: yes

#89 Sync Release tools repo subtree
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
Labels: release-note-none, size/XS, approved, lgtm, needs-ok-to-test, cncf-cla: yes

#91 Bump up grpc-health-probe in Dockerfile to v0.4.36
  cmd/csi-snapshot-metadata/Dockerfile
Labels: release-note-none, size/XS, approved, lgtm, cncf-cla: yes

#86 Client error propagation
  pkg/internal/server/grpc/common_test.go
  pkg/internal/server/grpc/get_metadata_allocated.go
  pkg/internal/server/grpc/get_metadata_allocated_test.go
  pkg/internal/server/grpc/get_metadata_delta.go
  pkg/internal/server/grpc/get_metadata_delta_test.go
  pkg/internal/server/grpc/server.go
  pkg/internal/server/grpc/server_test.go
  pkg/sidecar/sidecar.go
  pkg/sidecar/sidecar_test.go
Labels: release-note-none, kind/cleanup, approved, lgtm, size/XL, cncf-cla: yes

#90 Correct kubeclient init and parameters in snapshot-metadata-lister
  examples/snapshot-metadata-lister/main.go
  pkg/iterator/common_test.go
  pkg/iterator/iter.go
  pkg/iterator/iter_test.go
Labels: release-note-none, approved, lgtm, size/S, cncf-cla: yes
