Repository kubernetes-csi/external-snapshot-metadata, pull requests merged in 2024-11, with the labels that each got.

#60 add "./.cloudbuild.sh" symlink needed to build images
  .cloudbuild.sh
Labels: release-note-none, ok-to-test, kind/failing-test, size/XS, approved, lgtm, cncf-cla: yes

#61 Add hairyhum to owners list
  OWNERS
Labels: release-note-none, size/XS, approved, lgtm, cncf-cla: yes

#63 test: Set trivy repository to avoid rate limiting
  .github/workflows/trivy.yaml
Labels: release-note-none, kind/failing-test, size/XS, approved, lgtm, cncf-cla: yes

#69 Use CSI Hostpath driver in example
  deploy/example/backup-app/cluster-role-binding.yaml
  deploy/example/csi-driver/README.md
  deploy/example/csi-driver/csi-driver-cluster-role-binding.yaml
  deploy/example/csi-driver/csi-driver-service-account.yaml
  deploy/example/csi-driver/csi-driver-service.yaml
  deploy/example/csi-driver/csi-driver-with-snapshot-metadata-sidecar.yaml
  deploy/snapshot-metadata-client-cluster-role.yaml
  deploy/snapshot-metadata-cluster-role.yaml
Labels: release-note-none, size/L, kind/documentation, approved, lgtm, cncf-cla: yes

#72 api: add api-approved.kubernetes.io annotation to CRD
  client/config/crd/cbt.storage.k8s.io_snapshotmetadataservices.yaml
Labels: kind/bug, release-note-none, ok-to-test, size/XS, approved, lgtm, cncf-cla: yes

#80 The snapshot iterator now determines the ServiceAccount if unspecified.
  examples/snapshot-metadata-lister/main.go
  pkg/iterator/common_test.go
  pkg/iterator/iter.go
  pkg/iterator/iter_test.go
Labels: release-note-none, size/L, kind/cleanup, approved, lgtm, cncf-cla: yes
