Repository kubernetes-csi/external-snapshot-metadata, pull requests merged in 2024-10, with the labels that each got.

#45 ci: add codespell github action
  .github/workflows/codespell.yml
  pkg/internal/server/grpc/get_metadata_allocated_test.go
  pkg/internal/server/grpc/get_metadata_delta_test.go
Labels: release-note-none, approved, lgtm, size/S, cncf-cla: yes

#46 Sync dependabot config from other sidecars repository
  .github/dependabot.yaml
Labels: release-note-none, size/M, approved, lgtm, cncf-cla: yes

#47 sync issue and pr template from external-snapshotter repo
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/support.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release-note-none, size/M, approved, lgtm, cncf-cla: yes

#48 add trivy vulnerability scanner github action
  .github/workflows/trivy.yaml
  cmd/csi-snapshot-metadata/Dockerfile
Labels: release-note-none, size/M, approved, lgtm, cncf-cla: yes

#49 Log stream responses with progress.
  .prow.sh
  Makefile
  pkg/internal/server/grpc/common_test.go
  pkg/internal/server/grpc/get_metadata_allocated.go
  pkg/internal/server/grpc/get_metadata_allocated_test.go
  pkg/internal/server/grpc/get_metadata_delta.go
  pkg/internal/server/grpc/get_metadata_delta_test.go
  pkg/internal/server/grpc/server.go
  pkg/internal/server/grpc/status.go
Labels: release-note-none, size/L, approved, lgtm, cncf-cla: yes

#55 Fixed linter issues; added gci and importas rules.
  .golangci.yml
  pkg/internal/authn/token_auth.go
  pkg/internal/authn/token_auth_test.go
  pkg/internal/authz/sar_authorizer.go
  pkg/internal/authz/sar_authorizer_test.go
  pkg/internal/runtime/test_harness.go
  pkg/internal/server/grpc/auth.go
  pkg/internal/server/grpc/common_test.go
  pkg/internal/server/grpc/get_metadata_allocated.go
  pkg/internal/server/grpc/get_metadata_allocated_test.go
  pkg/internal/server/grpc/get_metadata_delta.go
  pkg/internal/server/grpc/get_metadata_delta_test.go
  pkg/internal/server/grpc/health.go
  pkg/internal/server/grpc/server.go
  pkg/internal/server/grpc/snapshot.go
  pkg/internal/server/grpc/snapshotter_secret.go
  pkg/internal/server/grpc/snapshotter_secret_test.go
  pkg/internal/server/grpc/status.go
  pkg/sidecar/sidecar.go
Labels: release-note-none, size/L, kind/cleanup, approved, lgtm, cncf-cla: yes
