Repository kubernetes-csi/external-snapshot-metadata, pull requests merged in 2024-07, with the labels that each got.

#3 Skeleton main runtime
  cmd/csi-snapshot-metadata/Dockerfile
  cmd/csi-snapshot-metadata/main.go
  go.mod
  go.sum
  pkg/internal/runtime/runtime.go
  pkg/internal/runtime/runtime_test.go
  pkg/sidecar/sidecar.go
Labels: release-note-none, approved, lgtm, size/XL, cncf-cla: yes

#4 Add grpc server for SnapshotMetadata service
  Makefile
  pkg/api/schema.pb.go
  pkg/api/schema_grpc.pb.go
  pkg/internal/server/grpc/server.go
  pkg/internal/server/grpc/server_test.go
  pkg/internal/server/grpc/snaphotmetadata_handlers.go
  pkg/sidecar/sidecar.go
  proto/schema.proto
Labels: release-note-none, size/L, approved, lgtm, cncf-cla: yes

#5 Check that the CSI driver supports the SnapshotMetadata service.
  go.mod
  go.sum
  pkg/internal/runtime/runtime.go
  pkg/internal/runtime/runtime_test.go
  pkg/sidecar/sidecar.go
Labels: release-note-none, size/M, approved, lgtm, cncf-cla: yes

#7 Add authentication and authorization layer
  go.mod
  go.sum
  pkg/internal/authn/token_auth.go
  pkg/internal/authn/token_auth_test.go
  pkg/internal/authz/sar_authorizer.go
  pkg/internal/authz/sar_authorizer_test.go
  pkg/internal/runtime/runtime.go
  pkg/internal/runtime/runtime_test.go
  pkg/internal/server/grpc/server.go
  pkg/internal/server/grpc/server_test.go
  pkg/internal/server/grpc/snaphotmetadata_handlers.go
  pkg/sidecar/sidecar.go
Labels: release-note-none, approved, lgtm, size/XL, cncf-cla: yes

#16 Refactored server/grpc to use the sidecar runtime structure
  pkg/internal/runtime/runtime.go
  pkg/internal/runtime/runtime_test.go
  pkg/internal/server/grpc/auth.go
  pkg/internal/server/grpc/auth_test.go
  pkg/internal/server/grpc/common_test.go
  pkg/internal/server/grpc/server.go
  pkg/internal/server/grpc/server_test.go
  pkg/internal/server/grpc/snaphotmetadata_handlers.go
  pkg/internal/server/grpc/snapshotmetadata_handlers_test.go
  pkg/internal/server/grpc/status_msgs.go
  pkg/internal/server/grpc/validators.go
  pkg/internal/server/grpc/validators_test.go
  pkg/sidecar/sidecar.go
Labels: release-note-none, approved, lgtm, size/XXL, cncf-cla: yes
