Repository kubernetes-csi/external-snapshot-metadata, pull requests merged in 2024-09, with the labels that each got.

#28 Fix gRPC handler unit tests
  pkg/internal/runtime/runtime_test.go
  pkg/internal/runtime/test_harness.go
  pkg/internal/runtime/test_harness_test.go
  pkg/internal/server/grpc/auth_test.go
  pkg/internal/server/grpc/common_test.go
  pkg/internal/server/grpc/health_test.go
  pkg/internal/server/grpc/snapshotmetadata_handlers_test.go
  pkg/internal/server/grpc/validators_test.go
Labels: release-note-none, size/L, approved, lgtm, cncf-cla: yes

#32 Propagate gRPC Status errors
  pkg/internal/server/grpc/get_metadata_allocated.go
  pkg/internal/server/grpc/get_metadata_allocated_test.go
  pkg/internal/server/grpc/get_metadata_delta.go
  pkg/internal/server/grpc/get_metadata_delta_test.go
  pkg/internal/server/grpc/status.go
  pkg/internal/server/grpc/status_test.go
Labels: release-note-none, size/L, approved, lgtm, cncf-cla: yes

#33 Add unit test for convertCSIRequest handlers
  pkg/internal/server/grpc/auth_test.go
  pkg/internal/server/grpc/common_test.go
  pkg/internal/server/grpc/get_metadata_allocated_test.go
  pkg/internal/server/grpc/get_metadata_delta.go
  pkg/internal/server/grpc/get_metadata_delta_test.go
  pkg/internal/server/grpc/health_test.go
  pkg/internal/server/grpc/status.go
Labels: release-note-none, approved, lgtm, size/XL, cncf-cla: yes

#34 Fetch the optional snapshotter secrets from the VolumeSnapshotClass.
  .gitignore
  go.mod
  go.sum
  pkg/internal/runtime/runtime.go
  pkg/internal/server/grpc/common_test.go
  pkg/internal/server/grpc/get_metadata_allocated.go
  pkg/internal/server/grpc/get_metadata_allocated_test.go
  pkg/internal/server/grpc/get_metadata_delta.go
  pkg/internal/server/grpc/get_metadata_delta_test.go
  pkg/internal/server/grpc/server.go
  pkg/internal/server/grpc/snapshot.go
  pkg/internal/server/grpc/snapshotter_secret.go
  pkg/internal/server/grpc/snapshotter_secret_test.go
  pkg/internal/server/grpc/status.go
Labels: release-note-none, approved, lgtm, size/XXL, cncf-cla: yes

#38 Verify base and target snapshot belong to the same volume
  pkg/internal/server/grpc/get_metadata_delta.go
  pkg/internal/server/grpc/get_metadata_delta_test.go
  pkg/internal/server/grpc/snapshot.go
  pkg/internal/server/grpc/status.go
Labels: release-note-none, size/M, approved, lgtm, cncf-cla: yes

#37 Use a contextual logger in the sidecar handlers.
  pkg/internal/authn/token_auth.go
  pkg/internal/authz/sar_authorizer.go
  pkg/internal/server/grpc/auth.go
  pkg/internal/server/grpc/get_metadata_allocated.go
  pkg/internal/server/grpc/get_metadata_delta.go
  pkg/internal/server/grpc/health.go
  pkg/internal/server/grpc/server.go
  pkg/internal/server/grpc/server_test.go
  pkg/internal/server/grpc/snapshot.go
  pkg/internal/server/grpc/snapshotter_secret.go
  pkg/internal/server/grpc/status.go
Labels: release-note-none, size/L, approved, lgtm, cncf-cla: yes

#42 Add unit tests for streaming data transefer
  pkg/csiclientmocks/client.go
  pkg/csiclientmocks/client.mock.go
  pkg/internal/server/grpc/get_metadata_allocated_test.go
  pkg/internal/server/grpc/get_metadata_delta_test.go
  pkg/k8sclientmocks/client.go
  pkg/k8sclientmocks/client.mock.go
Labels: release-note-none, approved, lgtm, size/XXL, cncf-cla: yes

#43 build: Add golangci-lint make target
  .golangci.yml
  Makefile
Labels: release-note-none, size/M, approved, lgtm, cncf-cla: yes
