Repository kubernetes-csi/external-snapshot-metadata, pull requests merged in 2025-01, with the labels that each got.

#98 temporarily pause trivy github action
  .github/workflows/trivy.yaml
Labels: release-note-none, kind/failing-test, size/XS, approved, lgtm, cncf-cla: yes

#101 Fix timeout duration calculation
  pkg/sidecar/sidecar.go
  pkg/sidecar/sidecar_test.go
Labels: kind/bug, release-note-none, size/XS, approved, lgtm, cncf-cla: yes

#93 Add snapshot-metadata-lister pod deployment
  examples/snapshot-metadata-lister/deploy/snapshot-metadata-lister-pod.yaml
Labels: release-note-none, size/M, approved, lgtm, cncf-cla: yes

#102 add rakshith-r to owners list
  OWNERS
Labels: release-note-none, size/XS, approved, lgtm, cncf-cla: yes

#94 Bump up golang.org/x/net dep to v0.33.0
  go.mod
  go.sum
Labels: release-note-none, approved, lgtm, size/S, cncf-cla: yes

#104 Update go version to match that used in CI.
  go.mod
Labels: release-note-none, size/XS, kind/cleanup, approved, lgtm, cncf-cla: yes

#68 add integration test github action
  .github/workflows/integration-test.yaml
  deploy/example/backup-app/testdata/backup-app-pod.yaml
  scripts/deploy-snapshot-controller.sh
Labels: release-note-none, size/L, ok-to-test, approved, lgtm, cncf-cla: yes

#107 update grpc-health-probe and re-enable triv scanner gh action
  .github/workflows/trivy.yaml
  cmd/csi-snapshot-metadata/Dockerfile
Labels: release-note-none, kind/failing-test, size/XS, approved, lgtm, cncf-cla: yes

#78 metrics: add utility to record metrics for sidecar
  pkg/internal/runtime/runtime.go
  pkg/internal/runtime/test_harness.go
  pkg/internal/runtime/util_metrics.go
  pkg/internal/server/grpc/common_test.go
  pkg/internal/server/grpc/get_metadata_allocated.go
  pkg/internal/server/grpc/get_metadata_allocated_test.go
  pkg/internal/server/grpc/get_metadata_delta.go
  pkg/internal/server/grpc/get_metadata_delta_test.go
  pkg/sidecar/sidecar.go
  pkg/sidecar/sidecar_test.go
Labels: kind/feature, size/L, ok-to-test, release-note, approved, lgtm, cncf-cla: yes

#111 add CHANGELOG folder and CHANGELOG-0.1.md
  CHANGELOG/CHANGELOG-0.1.md
Labels: release-note-none, size/L, kind/documentation, approved, lgtm, cncf-cla: yes

#114 Use official kubernetes-csi/cs-driver-host-path repo for deployment
  .github/workflows/integration-test.yaml
Labels: release-note-none, size/XS, kind/cleanup, approved, lgtm, cncf-cla: yes

#116 test: update test certs and k8s tls secret
  deploy/example/csi-driver/testdata/certs/ca-cert.pem
  deploy/example/csi-driver/testdata/certs/server-cert.pem
  deploy/example/csi-driver/testdata/certs/server-key.pem
  deploy/example/csi-driver/testdata/csi-snapshot-metadata-tls-secret.yaml
  deploy/example/csi-driver/testdata/snapshotmetadataservice.yaml
Labels: kind/bug, release-note-none, size/L, ok-to-test, approved, lgtm, cncf-cla: yes
