Repository kubernetes-csi/external-snapshot-metadata, pull requests merged in 2025-02, with the labels that each got.

#124 Prow update master
  release-tools/prow.sh
Labels: release-note-none, ok-to-test, size/XS, kind/cleanup, approved, lgtm, cncf-cla: yes

#117 Add verify functionality to snapshot-metadata-lister tool
  .github/workflows/integration-test.yaml
  .github/workflows/trivy.yaml
  deploy/example/backup-app/testdata/backup-app-pod.yaml
  examples/snapshot-metadata-verifier/main.go
  pkg/iterator/common_test.go
  pkg/iterator/emitters.go
  pkg/iterator/emitters_test.go
  pkg/iterator/iter.go
  pkg/iterator/iter_test.go
Labels: kind/feature, release-note-none, approved, lgtm, size/XL, cncf-cla: yes

#127 Document snapshot-metadata-verifier command
  README.md
Labels: release-note-none, kind/documentation, size/XS, approved, lgtm, cncf-cla: yes
